# Generated by Django 5.2.8 on 2025-12-11 11:42

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.attachment_upload_to)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='ticket',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='raw_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Message-ID from incoming email (used to prevent duplicates).', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sender',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='web', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='thread_id',
            field=models.CharField(blank=True, help_text='Optional: used for grouping email threads.', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['raw_message_id'], name='tickets_tic_raw_mes_4d7c8b_idx'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
    ]
