# Generated by Django 5.2.8 on 2025-12-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_created_by_ticket_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raw_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique Message-ID from incoming email to prevent duplicates.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address of the sender if ticket was created via email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='web', help_text='web / email / api', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='thread_id',
            field=models.CharField(blank=True, help_text='Optional email thread/conversation ID.', max_length=255),
        ),
    ]
