# Generated by Django 5.2.8 on 2026-01-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_priority_alter_ticket_raw_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_status_b256f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_raw_mes_4d7c8b_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='raw_message_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='thread_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='web', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('on_hold', 'On Hold'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=30),
        ),
    ]
